# Generated by Django 5.0 on 2023-12-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LLMChat", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geminibot",
            name="question",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="geminibot",
            name="response",
            field=models.TextField(),
        ),
    ]
